### ISSUE TITLE
Issue with Nexus3 Plugin and SHA256 

### ISSUE THREAD

**Issue by iphonesunil** [phreakadelle/maven-artifact-choicelistprovider-plugin#17]
Hi,
I am using version 3.15.2 of nexus and when using this plugin with jenkins i get the below error.

org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestApiSearchService callService
WARNING: failed to map
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "sha256" (class org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Checksum), not marked as ignorable (2 known properties: "sha1", "md5"])
 at [Source: (StringReader); line: 10, column: 19] (through reference chain: org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestResponse["items"]->java.lang.Object[][0]->org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item["checksum"]->org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Checksum["sha256"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)

Any idea how this problem can be solved?

**Comment by iphonesunil** [comment]
Managed to fix this using the attached file, however I cannot submit pull requests to your project
Rename attached file to .java

Thanks,

[Checksum.txt](https://github.com/phreakadelle/maven-artifact-choicelistprovider-plugin/files/3119185/Checksum.txt)

**Comment by phreakadelle** [comment]
Hey Sunil, thanks for your support.

I am wondering that the REST API returns the field sha256. This seems to be new and also not documented here: https://help.sonatype.com/repomanager3/rest-and-integration-api/search-api

Please try again to raise a Pull Request. It should be possible for everyone. Maybe you need to fork the repo first?

Regards
Stephan

**Comment by iphonesunil** [comment]
Hey Stephan,
Yes. This was indeed the REST API fetching this from Nexus3. I have raised a Pull request now. Please check and merge. Once we have a new version on Jenkins, I will install from official channels again.

Thanks,

**Comment by phreakadelle** [comment]
I've merged your PR and published version 1.5.0

Thanks for your support!
